const necrons = {
  units: [
    { name: "Anrakyr the Traveller", min: 1, max: 1, points: 167 },
    { name: "C’tan Shard of the Deceiver", min: 1, max: 1, points: 225 },
    { name: "C’tan Shard of the Nightbringer", min: 1, max: 1, points: 210 },
    { name: "Illuminor Szeras", min: 1, max: 1, points: 143 },
    { name: "Imotekh the Stormlord", min: 1, max: 1, points: 200 },
    { name: "Nemesor Zahndrekh", min: 1, max: 1, points: 180 },
    { name: "Orikan the Diviner", min: 1, max: 1, points: 115 },
    { name: "Trazyn the Infinite", min: 1, max: 1, points: 100 },
    { name: "Vargard Obyron", min: 1, max: 1, points: 140 },
    { name: "Catacomb Command Barge", min: 1, max: 1, points: 138 },
    { name: "Cryptek", min: 1, max: 1, points: 70 },
    { name: "Destroyer Lord", min: 1, max: 1, points: 110 },
    { name: "Lord", min: 1, max: 1, points: 73 },
    { name: "Overlord", min: 1, max: 1, points: 84 },
    { name: "Deathmarks", min: 5, max: 10, points: 19 },
    { name: "Immortals", min: 5, max: 10, points: 8 },
    { name: "Lychguard", min: 5, max: 10, points: 19 },
    { name: "Necron Warriors", min: 10, max: 20, points: 12 },
    { name: "Flayed Ones", min: 5, max: 20, points: 17 },
    { name: "Triarch Praetorians", min: 5, max: 10, points: 22 },
    { name: "Triarch Stalker", min: 1, max: 1, points: 117 },
    { name: "Canoptek Scarabs", min: 3, max: 9, points: 13 },
    { name: "Canoptek Wraiths", min: 3, max: 6, points: 55 },
    { name: "Destroyers", min: 1, max: 6, points: 30 },
    { name: "Tomb Blades", min: 3, max: 9, points: 14 },
    { name: "Annihilation Barge", min: 1, max: 1, points: 133 },
    { name: "Canoptek Spyders", min: 1, max: 3, points: 65 },
    { name: "Doomsday Ark", min: 1, max: 1, points: 193 },
    { name: "Heavy Destroyers", min: 1, max: 3, points: 30 },
    { name: "Monolith", min: 1, max: 1, points: 381 },
    { name: "Transcendent C’tan", min: 1, max: 1, points: 225 },
    { name: "Ghost Ark", min: 1, max: 1, points: 160 },
    { name: "Doom Scythe", min: 1, max: 1, points: 205 },
    { name: "Night Scythe", min: 1, max: 1, points: 160 },
    { name: "Obelisk", min: 1, max: 1, points: 426 },
    { name: "Tesseract Vault", min: 1, max: 1, points: 496 }
  ],
  weapons: {
    shooting: [
      { name: "Death ray", points: 0 },
      { name: "Doomsday cannon", points: 0 },
      { name: "Gauss blaster", points: 9 },
      { name: "Gauss cannon", points: 20 },
      { name: "Gauss Flayer", points: 0 },
      { name: "Gauss Flayer array", points: 0 },
      { name: "Gauss Flux arc", points: 0 },
      { name: "Heat ray", points: 54 },
      { name: "Heavy gauss cannon", points: 27 },
      { name: "Particle beamer", points: 10 },
      { name: "Particle caster", points: 4 },
      { name: "Particle shredder", points: 41 },
      { name: "Particle whip", points: 0 },
      { name: "Rod of covenant", points: 10 },
      { name: "Staff of light", points: 10 },
      { name: "Synaptic disintegrator", points: 0 },
      { name: "Tesla cannon", points: 13 },
      { name: "Tesla carbine", points: 9 },
      { name: "Tesla destructor", points: 0 },
      { name: "Tesla sphere", points: 0 },
      { name: "Transdimensional beamer", points: 14 },
      { name: "Twin heavy gauss cannon", points: 54 },
      { name: "Twin tesla destructor", points: 0 }
    ],
    melee: [
      { name: "Automaton claws", points: 0 },
      { name: "Crackling tendrils", points: 0 },
      { name: "Feeder mandibles", points: 0 },
      { name: "Flayer claws", points: 0 },
      { name: "Hyperphase sword", points: 3 },
      { name: "Massive forelimbs", points: 0 },
      { name: "Vicious claws", points: 0 },
      { name: "Voidblade", points: 6 },
      { name: "Voidscythe", points: 20 },
      { name: "Warscythe", points: 11 },
      { name: "Whip coils", points: 9 },
      { name: "Dispersion shield", points: 12 },
      { name: "Chronometron", points: 15 },
      { name: "Canoptek cloak", points: 5 },
      { name: "Fabricator claw array", points: 5 },
      { name: "Gloom prism", points: 5 },
      { name: "Nebuloscope", points: 2 },
      { name: "Phylactery", points: 10 },
      { name: "Resurrection orb", points: 35 },
      { name: "Shadowloom", points: 5 },
      { name: "Shieldvanes", points: 3 }
    ]
  }
};
module.exports = { necrons };
